antifragile/Controllers/CartController.cs
using antifragile.Data.Interfaces;
using antifragile.Models;
using antifragile.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace antifragile.Controllers;

public class CartController : Controller
{
    public ICart _Cart;
    public IProducts _Products;

    public CartController(ICart cart, IProducts products)
    {
        _Products = products;
        _Cart = cart;
    }
    // GET
    public IActionResult Index()
    {
        if (HttpContext.User.Identity.IsAuthenticated == false)
        {
            return RedirectToAction("Login", "Profile");
        }
        
        List<Product> products = _Cart.productsInCart;
        var cvm = new CartViewModel()
        {
            cartProducts = products
        };
        return View(cvm);
    }

    [Route("Cart/add/{prodId?}")]
    public IActionResult AddProductToCart(int prodId)
    {
        var product = _Products.AllProducts.First(p => p.id == prodId);
        _Cart.AddProductToCart(product);

        var cvm = new CartViewModel()
        {
            cartProducts = _Cart.productsInCart
        };
        
        return RedirectToAction("Index");
    }
}

antifragile/Controllers/CatalogController.cs
using antifragile.Data.Interfaces;
using antifragile.Models;
using antifragile.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace antifragile.Controllers;

public class CatalogController : Controller
{
    public IProducts _products;

    public CatalogController(IProducts products)
    {
        _products = products;
    }
    
    [HttpGet("Catalog/{category?}")]
    [HttpGet("Catalog/{category?}/{filter?}")]
    [HttpGet("Catalog/{filter?}/{category}")]
    public IActionResult Index(string author, string category)
    {
        IEnumerable<Product> prods = _products.AllProducts;
        
        prods = SortByCategory(category, prods);
        prods = SortByAuthor(author, prods);
        
        
        var prodViewMod = new ProductsViewModel()
        {
            allProducts = prods,
        };

        return View(prodViewMod);
    }

    public IEnumerable<Product> SortByCategory(string category, IEnumerable<Product> prods)
    {
        if (string.IsNullOrEmpty(category))
        {
            return prods;
        }
        else
        {
            prods = _products.ProductsOfCategory(category, prods);
            return prods;
        }
    }

    public IEnumerable<Product> SortByAuthor(string author, IEnumerable<Product> prods)
    {
        if (string.IsNullOrEmpty(author)==false)
        {
            var temp = new List<Product>();
            foreach (var VARIABLE in prods)
            {
                if (VARIABLE.Name.Contains(author))
                {
                    temp.Add(VARIABLE);
                }
            }
            prods = temp;
        }

        return prods;
    }

    [HttpGet("Catalog/productPage/{prodId?}")]
    public IActionResult ProductPage(int prodId)
    {
        var product = _products.AllProducts.First(p => p.id == prodId);

        ProductPageViewModel ppvm = new ProductPageViewModel()
        {
            Name = product.Name,
            Price = product.Price,
            Description = product.Description,
            Pic = product.PicPath
        };
        return View(ppvm);
    }
}

antifragile/Controllers/FAQController.cs
using Microsoft.AspNetCore.Mvc;

namespace antifragile.Controllers;

public class FAQController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

antifragile/Views/Shared/Navbar.cshtml
<div class="header">
    <div class="header-section">
        <div class="header-item logo">
            Antifragile
        </div>
        <div class="header-item link">
            <a asp-controller="Catalog" asp-action="Index">Каталог</a>
        </div>
        <div class="header-item link">
            <a asp-controller="FAQ" asp-action="Index">FAQ</a>
        </div>
        <div class="header-item link">
            <a asp-controller="Catalog" asp-action="Index">Каталог</a>
        </div>
        <div class="header-item link">
            <a asp-controller="Catalog" asp-action="Index">Каталог</a>
        </div>
    </div>
    <div class="header-section">
        <div class="header-item img">
            <a asp-controller="Profile" asp-action="Index">
                <img src="/imgs/profile-icon.png"/>
            </a>
        </div>
        <div class="header-item img">
            <a asp-controller="Profile" asp-action="Index">
                <img src="/imgs/profile-icon.png"/>
            </a>
        </div>
    </div>
</div>

antifragile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - antifragile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/antifragile.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/header.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a id="header-title" class="navbar-brand left-compartment" asp-controller="Home" asp-action="Index">antifragile</a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto center-compartment">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Catalog" asp-action="Index">Каталог</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="FAQ" asp-action="">FAQ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Payment">Оплата</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Home" asp-action="Delivery">Доставка</a>
            </li>
        </ul>
        <div class="navbar-nav ml-auto right-compartment">
            <a class="nav-link" asp-controller="Cart" asp-action="Index">
                <i class="bi bi-cart4"></i>
            </a>
            <a class="nav-link" asp-controller="Profile" asp-action="Login">
                <i class="bi bi-person-circle"></i>
            </a>
        </div>
    </div>
</nav>

<div class="container" style="padding-bottom: 350px">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer id="footer" class="footer text-light">
    <div class="row">
        <div class="col-md-4">
            <h5>antifragile</h5>
        </div>
        <div class="col-md-auto">
            <h4>Меню</h4>
            <a class="nav-link" href="#" style="text-align: start">Каталог</a>
            <a class="nav-link" href="#">FAQ</a>
            <a class="nav-link" href="#">Оплата</a>
            <a class="nav-link" href="#">Доставка</a>
        </div>
        <div class="col-md-auto">
            <h4>Контакты</h4>
            <a class="nav-link" href="mailto:bibaboba@gmail.com">bibaboba@gmail.com</a>
            <a class="nav-link">+ 8 800 555 35 35</a>
        </div>
        <div class="col-md-auto">
            <h4>Наши соцсети</h4>
            <a class="nav-link">
                <i class="bi bi-instagram"></i>
            </a>
        </div>
    </div>
    <h4 id="date">2023</h4>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>